# NumPy

- Numerical Python.
- Bilimsel hesaplamalar için kullanılır.
- Çok boyutlu array ve matris üzerinde yüksek performanslı çalışma sağlar.
- Listelere benzerdir. Farkı veri saklama ve vektörel operasyonlardır.

In [1]:
# İki listeyi fonksiyon kullanarak çarpabiliriz.

a = [1,2,3,4]
b = [2,3,4,5]

ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [2]:
# Fonksiyon kullanmadan NumPy ile tanımlanmış şekilde de çarpabiliriz.

import numpy as np

a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

a * b

array([ 2,  6, 12, 20])

Klasik Python'da `list` esnektir ama veri saklama ve manipülatif işlemlerde maliyetli olduğu için NumPy'daki `array` yapısı daha işlevseldir, maliyeti azdır.

## Array oluşturmak

In [2]:
import numpy as np # NumPy ile çalışmak için import ile çağrılır.

a = np.array([12,3,4,6]) # Liste üzerinden array oluşturur.

print(a)
print(type(a)) # NumPy arraylerinin özel veri tipi ndarray.

[12  3  4  6]
<class 'numpy.ndarray'>


In [3]:
b = np.array([2.6, 5, 7.8, 4]) # ndarray verilerin tek tipte olmasını zorlar.

c = np.array([2.6, 5, 7.8, 4], dtype = 'int') # dtype argümanıyla ndarray tipleri istenilen formata getirilebilir.

print(b)
print(c)

[2.6 5.  7.8 4. ]
[2 5 7 4]


In [4]:
np.zeros(10, dtype='int') # Sıfırlardan oluşan bir array.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones(10) # Birlerden oluşan bir array.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full((3, 5), 7) # Belirli bir değerden oluşan matris şeklinde array.

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [9]:
np.arange(0, 10, 2) # Belirli aralıklarda doğrusal bir array.

array([0, 2, 4, 6, 8])

In [10]:
np.linspace(0, 1, 30) # Belirli sayılar arasında istenildiği kadar sayı üreten array.

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

## Array biçimlendirmek

- `ndim` : Boyut sayısı.
- `shape` : Boyut bilgisi.
- `size` : Toplam eleman sayısı.
- `dytpe` : Veri tipi.

In [2]:
import numpy as np

a = np.random.randint(10, size = (10, 5))

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[7 8 5 0 9]
 [8 0 0 7 5]
 [9 3 9 5 5]
 [7 5 5 2 2]
 [0 7 0 2 8]
 [2 7 0 5 1]
 [2 1 4 5 3]
 [4 6 4 1 5]
 [8 5 6 1 4]
 [5 7 4 2 9]]
2
(10, 5)
50
int64


In [9]:
a = np.arange(1, 10)
b = a.reshape(3, 3)

print(a, a.ndim)
print(b, b.ndim)

[1 2 3 4 5 6 7 8 9] 1
[[1 2 3]
 [4 5 6]
 [7 8 9]] 2


In [17]:
c = np.array([1,2,3])

d = c.reshape(1,3) # Vektör halindeki array matrise çevrildi. Ve boyutu da değişti.

print(c, c.ndim)
print(d, d.ndim)

[1 2 3] 1
[[1 2 3]] 2


In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = [7,8,9]

np.concatenate([x,y,z]) # Değerleri birleştirir.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
s = np.concatenate([x,y,z])

print(np.split(s, [3,6])) # Verilen index değerlerine göre ayırır.

d,e,f = np.split(s, [3, 6]) # Ayrılan array değerlerini kullanmak için de topluca değişkenlere atadı.

print(d)
print(e)
print(f)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]
[7 8 9]


In [26]:
v = np.array([34, 4, 1, 9, 10])

print(v)

print(np.sort(v)) # NumPy'daki metotla sıralar, array orjinalinde değişiklik yapmaz. v.sort() olsaydı kalıcı değişirdi.

print(np.argsort(v)) # Sıralama sonrası değerlerin eski index değerlerini, yani nerede olduklarını döndürür.

[34  4  1  9 10]
[ 1  4  9 10 34]
[2 1 3 4 0]


## Eleman işlemleri

In [3]:
import numpy as np

a = np.random.randint(10, size = 10)

print(a)

print(a[3]) # Array içindeki index değerine ulaşır.

print(a[-4]) # İndex değerine tersten ulaşır.

[1 1 1 9 6 1 7 1 0 6]
9
7


In [4]:
a[4] = 15 # Array içindeki değer yine atamayla değiştirilebilir.

print(a)

[ 1  1  1  9 15  1  7  1  0  6]


In [5]:
b = np.random.randint(10, size = (3, 5))

print(b)

[[7 1 7 0 2]
 [2 8 9 4 7]
 [1 3 3 6 8]]


In [7]:
print(b[1, 2]) # İki boyutlu array (matris) içindeki değerlere ulaşır.

b[0, 1] = 19

print(b[0, 1])

9
19


In [8]:
c = np.arange(20, 40)

c[3:8] # Dilimleme yöntemiyle array içinden istenilen değerlere ulaşır.

array([23, 24, 25, 26, 27])

Slice işlemleri `[satır:sütun]` şeklinde çalışır. 

In [3]:
d = np.random.randint(10, size = (5, 5))

print(d)

[[6 6 9 1 8]
 [7 6 5 2 5]
 [5 9 9 2 3]
 [3 7 8 6 4]
 [1 4 3 5 0]]


In [14]:
d[3,:] # Satırın tamamını alır.

array([0, 9, 1, 9, 0])

In [15]:
d[:,3] # Sütunun tamamını alır.

array([7, 3, 3, 9, 7])

İki boyutlu array içinden slice işlemi de `[satır:satır,sütun:sütun]` şeklinde çalışır. Aslında alt array oluşturur.

In [22]:
d[0:2,1:4] # Matrislerde önemli olan virgül. Kesişim kümesi gibi çalışıyor.

array([[2, 4, 7],
       [9, 1, 3]])

Alt arraylerde işlem yaparken ana arrayi etkilememek için alt array `copy` ile çoğaltılarak işlem yapılır.

In [24]:
print(d)

print(d[0:2,1:4])

alt = d[0:2,1:4].copy()

alt[0:1,1:] = 9999 # Alt arrayde değişiklik yapıyoruz.

print(alt)

print(d) # Ama yaptığımız değişiklik ana arrayi etkilemiyor.

[[8 2 4 7 0]
 [6 9 1 3 8]
 [2 1 4 3 3]
 [0 9 1 9 0]
 [0 5 1 7 2]]
[[2 4 7]
 [9 1 3]]
[[   2 9999 9999]
 [   9    1    3]]
[[8 2 4 7 0]
 [6 9 1 3 8]
 [2 1 4 3 3]
 [0 9 1 9 0]
 [0 5 1 7 2]]


Fancy Index kavramıyla bir array içinden eleman seçmek için o arraye liste veya array verilerek indexleme yapılabilir.

In [27]:
import numpy as np

f = np.arange(0, 500, 3)

index_deger = [2, 34, 23, 40]

f[index_deger]

array([  6, 102,  69, 120])

Koşullu eleman işlemleriyle array bazında sorgulama veya işlem yapılabilir.

`np.equal`
`np.not_equal`
`np.less_equal`
`np.less`
`np.greater`
`np.greater_equa`


Bu koşullu ifadeler aslında Python'ın temel operatörleriyle yapabileceğimiz şeyler.


## Matematiksel işlemler

In [2]:
import numpy as np

a = np.arange(5)

print(a)
print(a-1)
print(a+1)
print(a*3)
print(a**2)
print(a/2)

[0 1 2 3 4]
[-1  0  1  2  3]
[1 2 3 4 5]
[ 0  3  6  9 12]
[ 0  1  4  9 16]
[0.  0.5 1.  1.5 2. ]


Temel matematik operatörlerinin yanında bunlara has fonksiyonlar da var.

In [8]:
print(np.add(a,2)) # Toplama
print(np.subtract(a,2)) # Çıkarma
print(np.multiply(a,2)) # Çarpma
print(np.divide(a,2)) # Bölme
print(np.power(a,2)) # Üs

[2 3 4 5 6]
[-2 -1  0  1  2]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2. ]
[ 0  1  4  9 16]


## İstatistiksel işlemler

In [20]:
import numpy as np

b = np.random.normal(0,2, 30)

print(b)

print(np.mean(b)) # Ortalama
print(np.std(b)) # Standart sapma
print(np.var(b)) # Varyans
print(np.median(b)) # Ortanca
print(np.min(b)) # Minimum değer
print(np.max(b)) # Maksimum değer

print(np.sum(b)) # Değerleri toplar.

[ 2.36437334 -0.27972398  0.37239787 -2.40269174  1.64768722 -1.24815002
 -0.13053408 -3.1222714   0.62560829  0.66649763 -0.94068013  2.42670872
  3.04164785 -0.48308056  0.45795631 -1.88302371 -1.14559788 -1.07539564
  0.63979071  2.57519725 -2.41884116 -1.17873383 -1.50312043 -2.79702607
 -1.03584582 -1.1584882  -0.36389963  2.29871093 -3.2260122   2.21956678]
-0.23523245185695332
1.7776981153185631
3.1602105892071717
-0.42349009472071786
-3.2260122020641453
3.0416478545759906
-7.056973555708599


## Farklı boyutlardaki arrayler ile çalışmak (Broadcasting)

In [26]:
a = np.array([1,2,3])
m = np.ones((4,3))

print(a + m) # Tek boyutlu array diğerine satır satır boyutu ölçüşecek şekilde eklenir.

# Aynı boyutçaymışçasına eklenir. Broadcast yaymak manasına geliyor.

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
